using System.Linq;
using Content.Client._Scp.Decals; // Fire added - локализованные данные отображения декалей.
using Content.Client.Stylesheets;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Localization; // Fire added - разрешает подписи декалей без показа LocId.
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Decals.UI;

[GenerateTypedNameReferences]
public sealed partial class DecalPlacerWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _e = default!;
    [Dependency] private readonly ILocalizationManager _localization = default!; // Fire added

    private readonly DecalPlacementSystem _decalPlacementSystem;
    private readonly SpriteSystem _sprite;

    public FloatSpinBox RotationSpinBox;

    private PaletteColorPicker? _picker;

    private SortedDictionary<string, (Texture Texture, FireLocalizedDecalData Localization)>? _decals; // Fire edit
    private string? _selected;
    private string? _selectedCategory; // Fire added - технический тег выбранной локализованной категории.
    private Color _color = Color.White;
    private bool _useColor;
    private bool _snap;
    private float _rotation;
    private bool _cleanable;
    private int _zIndex;

    private bool _auto;

    public DecalPlacerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _decalPlacementSystem = _e.System<DecalPlacementSystem>();
        _sprite = _e.System<SpriteSystem>();

        // This needs to be done in C# so we can have custom stuff passed in the constructor
        // and thus have a proper step size
        RotationSpinBox = new FloatSpinBox(90.0f, 0)
        {
            HorizontalExpand = true
        };
        SpinBoxContainer.AddChild(RotationSpinBox);

        Search.OnTextChanged += _ => RefreshList();
        // Fire added start - видимый фильтр использует локализованную подпись и хранит технический тег в метаданных.
        CategoryFilter.OnItemSelected += args =>
        {
            CategoryFilter.SelectId(args.Id);
            var category = CategoryFilter.SelectedMetadata as string;
            _selectedCategory = string.IsNullOrEmpty(category) ? null : category;
            RefreshList();
        };
        // Fire added end
        ColorPicker.OnColorChanged += OnColorPicked;

        PickerOpen.OnPressed += _ =>
        {
            if (_picker is null)
            {
                _picker = new PaletteColorPicker();
                _picker.OpenToLeft();
                _picker.PaletteList.OnItemSelected += args =>
                {
                    var color = (args.ItemList.GetSelected().First().Metadata as Color?)!.Value;
                    ColorPicker.Color = color;
                    OnColorPicked(color);
                };
            }
            else
            {
                if (_picker.IsOpen)
                {
                    _picker.Close();
                }
                else
                {
                    _picker.Open();
                }
            }
        };

        RotationSpinBox.OnValueChanged += args =>
        {
            _rotation = args.Value;
            UpdateDecalPlacementInfo();
        };
        EnableAuto.OnToggled += args =>
        {
            _auto = args.Pressed;
            if (_selected != null)
                SelectDecal(_selected);
        };
        EnableColor.OnToggled += args =>
        {
            _useColor = args.Pressed;
            UpdateDecalPlacementInfo();
            RefreshList();
        };
        EnableSnap.OnToggled += args =>
        {
            _snap = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        EnableCleanable.OnToggled += args =>
        {
            _cleanable = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        ZIndexSpinBox.ValueChanged += args =>
        {
            _zIndex = args.Value;
            UpdateDecalPlacementInfo();
        };
    }

    private void OnColorPicked(Color color)
    {
        _color = color;
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    private void UpdateDecalPlacementInfo()
    {
        if (_selected is null)
            return;

        var color = _useColor ? _color : Color.White;
        _decalPlacementSystem.UpdateDecalInfo(_selected, color, _rotation, _snap, _zIndex, _cleanable);
    }

    private void RefreshList()
    {
        // Clear
        Grid.RemoveAllChildren();
        if (_decals == null)
            return;

        var filter = Search.Text;
        // Fire edit start - локализуем видимые имена и категории, сохраняя технический ID для выбора.
        foreach (var (_, entry) in _decals.OrderBy(
                     pair => pair.Value.Localization.DisplayName))
        {
            var (tex, localization) = entry;
            if (!localization.MatchesCategory(_selectedCategory) || !localization.MatchesSearch(filter))
                continue;

            var button = new TextureButton
            {
                TextureNormal = tex,
                Name = localization.TechnicalId,
                ToolTip = localization.DisplayName,
                Modulate = _useColor ? _color : Color.White
            };
            button.OnPressed += ButtonOnPressed;
            if (_selected == localization.TechnicalId)
            {
                var panelContainer = new PanelContainer
                {
                    Children =
                    {
                        button
                    }
                };
                panelContainer.SetOnlyStyleClass(StyleClass.PanelLight);
                Grid.AddChild(panelContainer);
            }
            else
                Grid.AddChild(button);
        }
        // Fire edit end
    }

    private void ButtonOnPressed(ButtonEventArgs obj)
    {
        if (obj.Button.Name == null)
            return;

        SelectDecal(obj.Button.Name);
    }

    private void SelectDecal(string decalId)
    {
        if (!_prototype.TryIndex<DecalPrototype>(decalId, out var decal))
            return;

        _selected = decalId;

        if (_auto)
        {
            EnableCleanable.Pressed = decal.DefaultCleanable;
            EnableColor.Pressed = decal.DefaultCustomColor;
            EnableSnap.Pressed = decal.DefaultSnap;
            _cleanable = decal.DefaultCleanable;
            _useColor = decal.DefaultCustomColor;
            _snap = decal.DefaultSnap;
        }
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    public void Populate(IEnumerable<DecalPrototype> prototypes)
    {
        // Fire edit start - создаём локализованные данные отображения без изменения ID прототипов.
        _decals = new SortedDictionary<string, (Texture Texture, FireLocalizedDecalData Localization)>();
        var categories = new Dictionary<string, string>();
        foreach (var decalPrototype in prototypes)
        {
            if (!decalPrototype.ShowMenu)
                continue;

            var humanName = FireDecalLocalization.HumanizeIdentifier(decalPrototype.ID);
            var localizedName = FireDecalLocalization.GetDecalName(
                _localization,
                decalPrototype.ID,
                humanName);
            var localizedCategories = decalPrototype.Tags
                .Select(tag =>
                {
                    var localizedCategory = FireDecalLocalization.GetCategoryName(
                        _localization,
                        tag,
                        FireDecalLocalization.HumanizeIdentifier(tag));
                    categories.TryAdd(tag, localizedCategory);
                    return localizedCategory;
                })
                .ToArray();
            var localizedDecal = new FireLocalizedDecalData(
                decalPrototype.ID,
                localizedName,
                localizedCategories,
                decalPrototype.Tags.ToHashSet());

            _decals.Add(
                decalPrototype.ID,
                (_sprite.Frame0(decalPrototype.Sprite), localizedDecal));
        }

        CategoryFilter.Clear();
        CategoryFilter.AddItem(_localization.GetString("decal-placer-window-category-all"));
        CategoryFilter.SetItemMetadata(0, string.Empty);
        foreach (var (technicalCategory, localizedCategory) in categories.OrderBy(
                     pair => pair.Value))
        {
            var index = CategoryFilter.ItemCount;
            CategoryFilter.AddItem(localizedCategory);
            CategoryFilter.SetItemMetadata(index, technicalCategory);
        }

        CategoryFilter.Select(0);
        _selectedCategory = null;
        // Fire edit end

        RefreshList();
    }

    protected override void Opened()
    {
        base.Opened();
        _decalPlacementSystem.SetActive(true);
    }

    public override void Close()
    {
        base.Close();
        _decalPlacementSystem.SetActive(false);
    }
}
