using Content.Client._Scp.Decals; // Fire added - общие правила локализации декалей.
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization; // Fire added
using Robust.Shared.Prototypes;

namespace Content.Client.Decals.UI;

[GenerateTypedNameReferences]
public sealed partial class PaletteColorPicker : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly ILocalizationManager _localization = default!; // Fire added

    private readonly TextureResource _tex;

    public PaletteColorPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _tex = _resourceCache.GetResource<TextureResource>("/Textures/Interface/Nano/button.svg.96dpi.png");

        var i = 0;
        foreach (var palette in _prototypeManager.EnumeratePrototypes<ColorPalettePrototype>())
        {
            // Fire edit start - отображаем локализованное имя, сохраняя прототип в метаданных.
            var paletteFallback = FireDecalLocalization.HumanizeIdentifier(palette.Name);
            var paletteName = FireDecalLocalization.GetPaletteName(
                _localization,
                palette.ID,
                paletteFallback);
            Palettes.AddItem(paletteName);
            // Fire edit end
            Palettes.SetItemMetadata(i, palette); // ew
            i += 1;
        }

        Palettes.OnItemSelected += args =>
        {
            Palettes.SelectId(args.Id);
            SetupList();
        };

        Palettes.Select(0);
        SetupList();
    }

    private void SetupList()
    {
        PaletteList.Clear();
        foreach (var (color, value) in (Palettes.SelectedMetadata as ColorPalettePrototype)!.Colors)
        {
            // Fire edit start - локализуем подпись цвета, не изменяя ключ или значение цвета.
            var colorFallback = FireDecalLocalization.HumanizeIdentifier(color);
            var colorName = FireDecalLocalization.GetColorName(
                _localization,
                color,
                colorFallback);
            var item = PaletteList.AddItem(colorName, _tex.Texture);
            // Fire edit end
            item.Metadata = value;
            item.IconModulate = value;
        }
    }
}
